// Generated by tools/generate_env_js.py — do not edit by hand
(function(){
  window.__KINGDOM_SUPABASE_CONFIG__ = window.__KINGDOM_SUPABASE_CONFIG__ || {
    url: 'https://invsxcmcczwckmfkynzk.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImludnN4Y21jY3p3Y2ttZmt5bnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3OTA0NzE0NTEsImV4cCI6MjEwNjA0NzQ1MX0._zv75lSG6VIkk_Fxoh_aH25NRHO1DvXyqBJwaT_2-YM'
  };
  window.__KINGDOM_CLOUDINARY_CONFIG__ = window.__KINGDOM_CLOUDINARY_CONFIG__ || {
    cloudName: 'z2geao1b',
    folder: '',
    transform: 'f_auto,q_auto'
  };
  window.__KINGDOM_APP_CONFIG__ = window.__KINGDOM_APP_CONFIG__ || {
    API_URL: 'http://127.0.0.1:5001',
    SITE_URL: 'http://127.0.0.1:8000'
  };
  console.log("env-config loaded: ", window.__KINGDOM_SUPABASE_CONFIG__ && window.__KINGDOM_SUPABASE_CONFIG__.url);
})();