// Generated by tools/generate_env_js.py — do not edit by hand
(function(){
  window.__KINGDOM_SUPABASE_CONFIG__ = window.__KINGDOM_SUPABASE_CONFIG__ || {
    url: 'https://spckgpxzcxvogjamfsqr.supabase.co',
    anonKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwY2tncHh6Y3h2b2dqYW1mc3FyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODg1NDg2NjQsImV4cCI6MjEwNDEyNDY2NH0.h52gkl9ms2vT785SUTmAT_IDzNfaa2jUpepEGIW0yZw'
  };
  window.__KINGDOM_APP_CONFIG__ = window.__KINGDOM_APP_CONFIG__ || {
    API_URL: 'http://127.0.0.1:5001',
    SITE_URL: 'http://127.0.0.1:8000'
  };
  console.log("env-config loaded: ", window.__KINGDOM_SUPABASE_CONFIG__ && window.__KINGDOM_SUPABASE_CONFIG__.url);
})();