import os
from pathlib import Path

def load_env(path):
    data = {}
    if not path.exists():
        return data
    for line in path.read_text(encoding='utf-8').splitlines():
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        k,v = line.split('=',1)
        v = v.strip().strip('"').strip("'")
        data[k.strip()] = v
    return data

repo_root = Path(__file__).resolve().parent.parent
env_local = repo_root / '.env.local'
env_file = repo_root / '.env'
# Prefer explicit .env (project dev file); fall back to .env.local
if env_file.exists():
    env = load_env(env_file)
else:
    env = load_env(env_local)

supabase_url = env.get('SUPABASE_URL') or env.get('SUPABASE_PROJECT_URL') or env.get('SUPABASE_PUBLIC_URL') or ''
anon = env.get('SUPABASE_ANON_KEY') or env.get('SUPABASE_PUBLIC_KEY') or env.get('SUPABASE_ANON') or ''
api_url = env.get('API_URL') or env.get('FLASK_API_URL') or ''
site_url = env.get('SITE_URL') or ''

out = []
out.append('// Generated by tools/generate_env_js.py — do not edit by hand')
out.append('(function(){')
out.append('  window.__KINGDOM_SUPABASE_CONFIG__ = window.__KINGDOM_SUPABASE_CONFIG__ || {')
out.append(f"    url: '{supabase_url.replace("'","\\'")}',")
out.append(f"    anonKey: '{anon.replace("'","\\'")}'")
out.append('  };')
out.append('  window.__KINGDOM_APP_CONFIG__ = window.__KINGDOM_APP_CONFIG__ || {')
out.append(f"    API_URL: '{api_url.replace("'","\\'")}',")
out.append(f"    SITE_URL: '{site_url.replace("'","\\'")}'")
out.append('  };')
out.append('  console.log("env-config loaded: ", window.__KINGDOM_SUPABASE_CONFIG__ && window.__KINGDOM_SUPABASE_CONFIG__.url);')
out.append('})();')

dest = repo_root / 'env-config.js'
dest.write_text('\n'.join(out), encoding='utf-8')
print('Wrote', dest)
